#!/usr/bin/env bash

cd "$(dirname ${BASH_SOURCE[0]})"
scripts_dir="$(pwd)/scripts"

${scripts_dir}/fetcher
${scripts_dir}/deploy

read -r -p "Do you want to enable hibernation ? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    ${scripts_dir}/enable-hibernation
fi

read -r -p "Do you want to install zsh ? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    ${scripts_dir}/install-antigen
fi

read -r -p "Do you want to reboot ? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    reboot
fi