#!/usr/bin/env bash

cd "$(dirname ${BASH_SOURCE[0]})"

sudo cp ../etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist

killall gpg-agent
sudo rm -rf /etc/pacman.d/gnupg
sudo rm -rf /root/.gnupg
sudo rm -rf $HOME/.gnupg
sudo pacman -Sc --noconfirm
sudo pacman-key --init
sudo pacman-key --populate archlinux
sudo pacman -Syy gnupg archlinux-keyring --noconfirm
# sudo pacman-key --refresh-keys
sudo pacman -Syyu --noconfirm
