#!/usr/bin/env bash

cd "$(dirname ${BASH_SOURCE[0]})"
basedir="$(pwd)"

pm=yay
storage_path="${basedir}/../storage/${pm}"
if ! command -v ${pm} &>/dev/null; then
    sudo pacman -Syu --noconfirm
    sudo pacman -S --needed --noconfirm base-devel git
    # sudo pacman -S --needed --noconfirm base-devel git rustup
    # rustup default stable

    if [ -d $storage_path ]; then
        rm -rf $storage_path
    fi
    cd ${basedir}/../storage
    git clone https://aur.archlinux.org/${pm}.git $storage_path
    cd $storage_path
    makepkg -si --noconfirm
fi

export package_manager=${pm}